<?php
global $cfg_Cs;
$cfg_Cs=array();
$cfg_Cs[1]=array(0,1,1,'5a2m6Zmi5a6e5pmv');
$cfg_Cs[2]=array(0,1,1,'5Z+56K6t6K++56iL');
$cfg_Cs[3]=array(0,1,1,'5ZCN5biI6aOO6YeH');
$cfg_Cs[4]=array(0,1,1,'5a2m5ZGY5Y+K5L2c5ZOB');
$cfg_Cs[5]=array(0,1,1,'6IGU57O75oiR5Lus');
$cfg_Cs[6]=array(0,1,0,'5Yib5Lia5Yqo5oCB');
$cfg_Cs[7]=array(0,1,1,'54OY54SZ56eY5pa5');
$cfg_Cs[8]=array(0,1,1,'5ZCN5biI6Kej5oOR');
$cfg_Cs[11]=array(0,1,0,'5LyY5oOg5rS75Yqo');
?>