<?php
$z[0]=Array("array","\n                if(@me['courseid']==\"11\")@me=\"HR.png\";\n                else if(@me['courseid']==\"10\")@me=\"D.png\";\n                else if(@me['courseid']==\"8\")@me=\"AA.png\";\n                ",0,230);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",371,388);
$z[2]=Array("arcurl","",441,456);
$z[3]=Array("coursephoto","",509,529);
$z[4]=Array("name","",584,597);
$z[5]=Array("description","",642,691);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",1010,1060);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>