<?php
$z[0]=Array("array","if(@me['courseid']=='10' || @me['courseid']=='11' || @me['courseid']=='12' || @me['courseid']=='8' || @me['courseid']=='20' || @me['courseid']=='40')@me='none';else @me='black';",19,236);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",358,375);
$z[2]=Array("arcurl","",428,443);
$z[3]=Array("coursephoto","",496,516);
$z[4]=Array("name","",604,617);
$z[5]=Array("description","",662,711);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",993,1043);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>