<?php
$z[0]=Array("array","if(@me['courseid']=='10' || @me['courseid']=='11')@me='none';else @me='black';",65,183);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",305,322);
$z[2]=Array("arcurl","",375,390);
$z[3]=Array("coursephoto","",443,463);
$z[4]=Array("name","",518,531);
$z[5]=Array("description","",576,625);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",944,994);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>