<?php
$z[0]=Array("chazhi","\$cateid=@me;if(\$cateid['courseid']=11)@me=\"up\";elseif(\$cateid['courseid']>0)@me=\"dowm\";else @me=\"ping\";",0,145);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",286,303);
$z[2]=Array("arcurl","",356,371);
$z[3]=Array("coursephoto","",424,444);
$z[4]=Array("name","",499,512);
$z[5]=Array("description","",557,606);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",925,975);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>