<?php
$z[0]=Array("array","\n                if(@me['courseid']==\"11\")@me='11';\n                ",0,108);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",249,266);
$z[2]=Array("arcurl","",319,334);
$z[3]=Array("coursephoto","",387,407);
$z[4]=Array("name","",462,475);
$z[5]=Array("description","",520,569);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",888,938);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>