<?php
$z[0]=Array("chazhi","\$cateid=@me;if(\$cateid['courseid']=11)@me=\$cateid['courseid'];elseif(\$cateid['courseid']>0)@me=\"dowm\";else @me=\"ping\";",0,160);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",301,318);
$z[2]=Array("arcurl","",371,386);
$z[3]=Array("coursephoto","",439,459);
$z[4]=Array("name","",514,527);
$z[5]=Array("description","",572,621);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",940,990);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>