<?php
$z[0]=Array("array","if(@me['courseid']=='10' || @me['courseid']=='11' || @me['courseid']=='12' || @me['courseid']=='8' || @me['courseid']=='20' || @me['courseid']=='40')\n                @me='';\n                else @me='\n                <li style=\"display:[field:array runphp='yes']if(@me['courseid']=='10' || @me['courseid']=='11' || @me['courseid']=='12' || @me['courseid']=='8' || @me['courseid']=='20' || @me['courseid']=='40')@me='none';else @me='black';",0,479);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",601,618);
$z[2]=Array("arcurl","",671,686);
$z[3]=Array("coursephoto","",739,759);
$z[4]=Array("name","",814,827);
$z[5]=Array("description","",872,921);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",1240,1290);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>