<?php
$z[0]=Array("array","\n                if(@me['courseid']==\"11\")@me=\"HR.png\";\n                ",0,112);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",253,270);
$z[2]=Array("arcurl","",323,338);
$z[3]=Array("coursephoto","",391,411);
$z[4]=Array("name","",466,479);
$z[5]=Array("description","",524,573);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",892,942);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>