<?php
$z[0]=Array("array","if(@me['courseid']=='10' || @me['courseid']=='11' || @me['courseid']=='12' || @me['courseid']=='8' || @me['courseid']=='20' || @me['courseid']=='40')\n                @me='none';\n                else @me='black';",0,251);
$z[0][4]['runphp']="yes";
$z[1]=Array("array","if(@me['courseid']=='10' || @me['courseid']=='11' || @me['courseid']=='12' || @me['courseid']=='8' || @me['courseid']=='20' || @me['courseid']=='40')@me='none';else @me='black';",287,504);
$z[1][4]['runphp']="yes";
$z[2]=Array("courseid","",626,643);
$z[3]=Array("arcurl","",696,711);
$z[4]=Array("coursephoto","",764,784);
$z[5]=Array("name","",839,852);
$z[6]=Array("description","",897,946);
$z[6][4]['function']="cn_substr(@me,50)";
$z[7]=Array("pubdate","",1265,1315);
$z[7][4]['function']="strftime('%Y-%m-%d',@me)";

?>