<?php
$z[0]=Array("array","\n                if(@me['courseid']==\"11\")@me=@me['courseid'];\n                ",0,119);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",260,277);
$z[2]=Array("arcurl","",330,345);
$z[3]=Array("coursephoto","",398,418);
$z[4]=Array("name","",473,486);
$z[5]=Array("description","",531,580);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",899,949);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>