<?php
$z[0]=Array("flag","\$flag=@me;if(\$flag==11)@me='1';else @me='2';",0,82);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",223,240);
$z[2]=Array("arcurl","",293,308);
$z[3]=Array("coursephoto","",361,381);
$z[4]=Array("name","",436,449);
$z[5]=Array("description","",494,543);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",862,912);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>