<li>
        <div class="am-gallery-item">
            <a href="[field:arcurl/]" class="">
              [field:image/]
                <div class="zxzxzx"><h3>[field:title/]</h3><p>[field:description function="cn_substr(@me,66)"/]...</p><button type="button" class="am-btn am-btn-default am-btn-xs am-round am-fr am-hide-sm">查看课程 -></button></div>
                <!--<div class="am-gallery-desc">[field:pubdate function=strftime('%Y-%m-%d',@me)/]</div>-->
            </a>
        </div>
      </li>