<?php
$z[0]=Array("flag","\$flag=@me;if(\$flag.courseid==11)@me='1';else @me='2';",0,91);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",232,249);
$z[2]=Array("arcurl","",302,317);
$z[3]=Array("coursephoto","",370,390);
$z[4]=Array("name","",445,458);
$z[5]=Array("description","",503,552);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",871,921);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>