<?php
$z[0]=Array("array","if(@me['courseid']=='10' || @me['courseid']=='11')@me='none';else @me='black';",107,225);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",347,364);
$z[2]=Array("arcurl","",417,432);
$z[3]=Array("coursephoto","",485,505);
$z[4]=Array("name","",560,573);
$z[5]=Array("description","",618,667);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",986,1036);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>