<?php
$z[0]=Array("array","if(@me['courseid']=='10' || @me['courseid']=='11')@me='none';else @me='black';",19,137);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",259,276);
$z[2]=Array("arcurl","",329,344);
$z[3]=Array("coursephoto","",397,417);
$z[4]=Array("name","",472,485);
$z[5]=Array("description","",530,579);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",898,948);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>