<?php
$z[0]=Array("array","if(@me['courseid']=='11')@me='none';else @me='display';",19,114);
$z[0][4]['runphp']="yes";
$z[1]=Array("courseid","",236,253);
$z[2]=Array("arcurl","",306,321);
$z[3]=Array("coursephoto","",374,394);
$z[4]=Array("name","",449,462);
$z[5]=Array("description","",507,556);
$z[5][4]['function']="cn_substr(@me,50)";
$z[6]=Array("pubdate","",875,925);
$z[6][4]['function']="strftime('%Y-%m-%d',@me)";

?>