<?php
$z[0]=Array("field","",166,191);
$z[0][4]['name']="description";
$z[1]=Array("field","",228,250);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",370,393);
$z[2][4]['name']="seotitle";
$z[3]=Array("global","",394,420);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",432,478);
$z[4][4]['filename']="tpl/common/head.php";
$z[5]=Array("arclist","\r\n	  <li>\r\n        <div class=\"am-gallery-item\">\r\n            <a href=\"[field:arcurl/]\" class=\"\">\r\n              [field:image/]\r\n                <h3 class=\"am-gallery-title\">[field:title/]</h3>\r\n                <div class=\"am-gallery-desc\">[field:pubdate function=strftime('%Y-%m-%d',@me)/]</div>\r\n            </a>\r\n        </div>\r\n      </li>\r\n      ",1087,1501);
$z[5][4]['titlelen']="";
$z[5][4]['infolen']="";
$z[5][4]['row']="99";
$z[6]=Array("include","",1522,1570);
$z[6][4]['filename']="tpl/common/footer.php";

?>