<?php
$z[0]=Array("field","",166,191);
$z[0][4]['name']="description";
$z[1]=Array("field","",228,250);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",373,393);
$z[2][4]['name']="title";
$z[3]=Array("global","",394,420);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",432,478);
$z[4][4]['filename']="tpl/common/head.php";
$z[5]=Array("field","",596,616);
$z[5][4]['name']="title";
$z[6]=Array("field","",674,700);
$z[6][4]['name']="description";
$z[7]=Array("type","[field:typelink /]",829,876);
$z[7][4]['row']="1";
$z[8]=Array("field","",878,900);
$z[8][4]['name']="typename";
$z[9]=Array("field","",931,951);
$z[9][4]['name']="title";
$z[10]=Array("field","",1000,1018);
$z[10][4]['name']="body";
$z[11]=Array("field","",1098,1120);
$z[11][4]['name']="typename";
$z[12]=Array("arclist","\r\n<div class=\"tpl-nav-detail-box\">\r\n <img src='[field:litpic/]' class=\"tpl-nav-img\" alt='[field:title function='html2text(@me)'/]'/><div class=\"tpl-nav-link\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n <div class=\"am-cf\"></div>\r\n </div>\r\n",1133,1438);
$z[12][4]['typeid']="";
$z[12][4]['titlelen']="42";
$z[12][4]['row']="99";
$z[13]=Array("include","",1481,1529);
$z[13][4]['filename']="tpl/common/footer.php";

?>