<?php
$z[0]=Array("field","",166,191);
$z[0][4]['name']="description";
$z[1]=Array("field","",228,250);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",370,393);
$z[2][4]['name']="seotitle";
$z[3]=Array("global","",394,420);
$z[3][4]['name']="cfg_webname";
$z[4]=Array("include","",432,478);
$z[4][4]['filename']="tpl/common/head.php";
$z[5]=Array("include","",1108,1156);
$z[5][4]['filename']="tpl/common/footer.php";

?>