<?php
$z[0]=Array("field","",166,191);
$z[0][4]['name']="description";
$z[1]=Array("field","",228,250);
$z[1][4]['name']="keywords";
$z[2]=Array("field","",316,332);
$z[2][4]['name']="id";
$z[3]=Array("field","",457,477);
$z[3][4]['name']="title";
$z[4]=Array("global","",478,504);
$z[4][4]['name']="cfg_webname";
$z[5]=Array("include","",516,562);
$z[5][4]['filename']="tpl/common/head.php";
$z[6]=Array("field","",680,700);
$z[6][4]['name']="title";
$z[7]=Array("field","",762,788);
$z[7][4]['name']="description";
$z[8]=Array("type","[field:typelink /]",920,967);
$z[8][4]['row']="1";
$z[9]=Array("field","",969,991);
$z[9][4]['name']="typename";
$z[10]=Array("field","",1022,1042);
$z[10][4]['name']="title";
$z[11]=Array("field","",1091,1110);
$z[11][4]['name']="body";
$z[12]=Array("field","",1198,1220);
$z[12][4]['name']="typename";
$z[13]=Array("arclist","\r\n<div class=\"tpl-nav-detail-box\">\r\n <img src='[field:litpic/]' class=\"tpl-nav-img\" alt='[field:title function='html2text(@me)'/]'/><div class=\"tpl-nav-link\"><a href=\"[field:arcurl/]\">[field:title/]</a></div>\r\n <div class=\"am-cf\"></div>\r\n </div>\r\n",1233,1538);
$z[13][4]['typeid']="";
$z[13][4]['titlelen']="42";
$z[13][4]['row']="99";
$z[14]=Array("include","",1581,1629);
$z[14][4]['filename']="tpl/common/footer.php";

?>